import Link from "next/link";
import { pick } from "@/lib/site-content";
import { ProjectPicture } from "@/app/_components/ProjectPicture";
import { ProjectMetrics } from "../ProjectMetrics";
import type { ProjectDetailProps } from "../types";
import { projectDetailData } from "../types";
import styles from "./project.module.css";

export default function GrowthOSProject(props: ProjectDetailProps){const{locale,project}=props;const{images,links,dir,previous,next,projectUrl}=projectDetailData(props);return <main className={styles.page} dir={dir}><nav className={styles.bar}><Link href={props.variantPath??`/${locale}`}>Back</Link><span>case.run</span></nav><header className={styles.product}><div><b>{pick(project.eyebrow,locale)}</b><h1>{pick(project.title,locale)}</h1><p>{pick(project.description,locale)}</p></div>{images[0]&&<ProjectPicture image={images[0]} locale={locale} className={styles.screen} priority/>}</header><section className={styles.pipeline}>{[["Challenge",project.challenge],["Solution",project.solution],["Implementation",project.implementation],["Outcome",project.outcome]].map(([l,t])=><article key={l as string}><h2>{locale==='ar'?({Challenge:'الأزمة',Solution:'الحل',Implementation:'التنفيذ',Outcome:'النتيجة'} as Record<string,string>)[l as string]:l as string}</h2><p>{pick(t,locale)}</p></article>)}</section><div className={styles.metrics}><ProjectMetrics project={project} locale={locale}/></div>{images.length>1&&<section className={styles.gallery}>{images.slice(1).map(img=><ProjectPicture key={img.id} image={img} locale={locale} className={styles.shot}/>)}</section>}<section className={styles.tools}>{project.tools.map(t=><span key={t}>{t}</span>)}{links.map(l=><a key={l.id} href={l.url} target="_blank" rel="noreferrer">{pick(l.label,locale)}</a>)}</section><nav className={styles.next}>{previous&&<Link href={projectUrl(previous.slug)}>← {pick(previous.title,locale)}</Link>}{next&&<Link href={projectUrl(next.slug)}>{pick(next.title,locale)} →</Link>}</nav></main>}
