import Image from "next/image";
import { PortraitImage } from "@/app/_components/PortraitImage";
import Link from "next/link";
import { pick } from "@/lib/site-content";
import { languageHref, projectHref, projectImages, publishedProjects, whatsappHref, type DesignProps } from "../types";
import s from "./retro-computer.module.css";

export default function RetroComputer(props:DesignProps){const{content,locale}=props;const projects=publishedProjects(content);return <main className={s.page} dir={locale==="ar"?"rtl":"ltr"}>
<div className={s.crt}/><nav><b>GROWTH_OS v20.26</b><div><span>● ONLINE</span><Link href={languageHref(props)}>[{locale==="ar"?"EN":"AR"}]</Link></div></nav>
<header className={s.desktop}><div className={s.icon}><span>▣</span><small>WORK.EXE</small></div><div className={s.window}><div className={s.bar}><span>PROFILE.TXT</span><b>_ □ ×</b></div><div className={s.windowBody}><div className={s.prompt}><span>C:\KHALID&gt; whoami</span><h1>{pick(content.profile.headline,locale)}</h1><p>{pick(content.profile.intro,locale)}</p><a href="#work">RUN PORTFOLIO.EXE ↵</a></div><div className={s.photo}><PortraitImage content={content} priority sizes="(max-width:760px) 82vw, 30vw" /></div></div></div><div className={s.taskbar}><span>START</span><i/>GROWTH_OS</div></header>
<section className={s.console}><div className={s.bar}><span>CAPABILITIES.CMD</span><b>_ □ ×</b></div><div className={s.consoleBody}><h2>C:\&gt; {pick(content.labels.services,locale)}</h2>{content.services.map(service=><article key={service.id}><span>[{service.number}]</span><div><h3>{pick(service.title,locale)}</h3><p>{pick(service.description,locale)}</p></div><b>READY</b></article>)}</div></section>
<section className={s.process}><div className={s.bar}><span>PROCESS.LOG</span><b>_ □ ×</b></div>{content.approach.map((item,i)=><article key={item.id}><span>{new Date(2026,0,i+1).toISOString().slice(0,10)} 0{i}:00</span><h3>{pick(item.title,locale)}</h3><p>{pick(item.description,locale)}</p></article>)}</section>
<section className={s.work} id="work"><header><span>DIRECTORY: C:\PORTFOLIO\CASES</span><h2>{pick(content.labels.work,locale)}</h2></header><div>{projects.map((project,i)=>{const cover=projectImages(project)[0];return <Link href={projectHref(project,props)} key={project.id} className={s.file}><div className={s.fileHead}><span>CASE_{String(i+1).padStart(2,"0")}.PROJ</span><b>OPEN ↗</b></div><div className={s.preview}>{cover?<Image src={cover.url} alt={pick(cover.alt,locale)} fill sizes="(max-width:760px) 100vw, 42vw" unoptimized/>:<span>NO_PREVIEW.BMP</span>}</div><h3>{pick(project.title,locale)}</h3><p>{pick(project.summary,locale)}</p></Link>})}</div></section>
<footer id="contact"><div className={s.bar}><span>NEW_MESSAGE.MSG</span><b>_ □ ×</b></div><div><p>&gt; {pick(content.labels.contactCopy,locale)}</p><h2>{pick(content.labels.contact,locale)}<i>_</i></h2><a href={`mailto:${content.profile.email}`}>MAILTO:{content.profile.email}</a><a href={whatsappHref(content)} target="_blank" rel="noreferrer">OPEN:WHATSAPP ↗</a></div></footer>
</main>}
